### ISSUE TITLE
Incorrect behavior of `LastInsertId`

### ISSUE THREAD

**Issue by kirillDanshin** [Boostport/avatica#3]
Now `LastInsertId` returns int64(0) and error with message that propose to get last sequence value but not ID of element that inserted at last transaction.

**Comment by F21** [comment]
Hey, thanks for opening this issue.

What do you propose to be the expected behavior? According to https://golang.org/pkg/database/sql/driver/#Result, `LastInsertId` should return the last value of the auto generated value. In Phoenix, auto generated ids are implemented as sequences(https://phoenix.apache.org/sequences.html). However, the server does not provide a mechanism to return this value, and the only way to get this value is to `SELECT` from the sequence. 

Unfortunately, this is not something that can be easily automated, because the sequence is separate from the table, and the name of the sequence is selected during the `UPSERT` by the user.
